### ISSUE TITLE
DAC.xml in separate folder

### ISSUE THREAD

**Issue by joel1979** [imi-bigpicture/slidetap#10]
According to WP2 submission [guidelines](https://bp.nbis.se/datasets/submission/preparation-guide.html) DAC.xml should be placed in a separate folder (PRIVATE) in the folder-structure, would be neat if this could be added in SlideTap.

**Comment by erikogabrielsson** [comment]
This is handled by [bigpicture_metadata_interface](https://github.com/imi-bigpicture/bigpicture-metadata-interface/tree/main), which has fixed the location of private metadata.
