### ISSUE TITLE
Feature Request: BPxml parsing

### ISSUE THREAD

**Issue by koellerMC** [imi-bigpicture/slidetap#2]
Description:
Standard Integration to import Bigpicture Datasets into Slides.

Behavior:

1. Selecting the dedicated dataset folder (containing files as outlined in the Bigpicture File Structure Standard).
2. All metadata is loaded into Slides and a new Project/Dataset is created.

**Comment by erikogabrielsson** [comment]
This feature is available in one of the [example apps of bigpicture-slidetap](https://github.com/imi-bigpicture/bigpicture-slidetap/tree/main/bigpicture_slidetap/apps/xml).
